import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { shadesOfPurple } from "@clerk/themes";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/layouts/header";
import { ThemeProvider } from "@/components/theme-provider";
import ConvexClientProvider from "./ConvexClientProvider";
import { Toaster } from "sonner";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={true}
          disableTransitionOnChange
        >
          {" "}
          <ClerkProvider
            appearance={{
              signIn: {
                baseTheme: [shadesOfPurple],
              },
              signUp: {
                baseTheme: [shadesOfPurple],
              },
            }}
          >
            <ConvexClientProvider>
              {" "}
              <main className="bg-slate-900 min-h-screen text-white overflow-x-hidden">
                <Header />
                {children}
                <Toaster />
              </main>
            </ConvexClientProvider>
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
